### Installation
- Use pip(Package Installer for Python)  
    - pip install numpy
    - pip install matplotlib
    ![use pip](https://user-images.githubusercontent.com/61931924/95999516-ebcae200-0e70-11eb-96f9-224cb48d2c5c.PNG)

### NumPy
- NumPy stands for 'Numerical Python'
    - A library consisting of multidimensional array objects and a collection of routines for processing of array
    
- Using NumPy, a developer can perform the follwing:
    - Mathematical and logical operations on arrays
    - Fourier transforms and routines for shape manipulation
    - Operations related to linear algebra
    - Random number generation

### Arrays
- The most important object defined in NumPy is the n-dimensional arrays type called __ndarray__
    - The elements of the array all have the same type
    - Items in the collections can be accessed using a zero-based index

In [8]:
import numpy as np

a = np.array([1,2,3])   # One-dimensional array
b = np.array([[1,2],
              [3,4]])   # Two dimensional array. 반드시 리스트 내에 포함해야 한다.
c = np.array([1,2,3,4,5], ndmin=2)   # To specify minimum number of dimensions
d = np.array([1,2,3], dtype=float)   # To specify desired data type for the array
print(a)
print(b)
print(c)
print(d)
a,b,c,d

[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1. 2. 3.]


(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]),
 array([[1, 2, 3, 4, 5]]),
 array([1., 2., 3.]))

여기서 말하는 dimension이란 차원의 수를 말하는데 2차원일 때는 행렬을 떠올리면 된다.

### Array Creation
- A new ndarray object can be constructed by any of the following array creation routines

In [9]:
import numpy as np

a = np.arange(5)        # Array of range(5)
b = np.arange(3,10,2)   # From 3 to 10 in increments of 2
c = np.zeros(5)   # Array of five zeros (default type is float)
d = np.ones(5)    # Array of five ones (default type is float)

print(a)
print(b)
print(c)
print(d)

a,b,c,d

[0 1 2 3 4]
[3 5 7 9]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


(array([0, 1, 2, 3, 4]),
 array([3, 5, 7, 9]),
 array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]))

np.arange , np.zeros , np.ones 세 가지를 제대로 알고 있자.

In [12]:
import numpy as np

a = np.eye(3)      # Produces square identity matrix
b = np.eye(3, 4)   # Identity matrix of size 3 × 4

# To produce an array of 5 elements equally spaced from 10 to 20
c = np.linspace(10, 20, 5)
d = np.linspace(10, 20, 3)

print(a)
print(b)
print(c)
print(d)
a,b,c,d


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[10.  12.5 15.  17.5 20. ]
[10. 15. 20.]


(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 array([10. , 12.5, 15. , 17.5, 20. ]),
 array([10., 15., 20.]))

### Getting Information and Changing Shapes
- We can get various information about an array and change its shape in a variety of ways

In [8]:
import numpy as np

a = np.arange(6)
print(a)

b = a.reshape(3,2)
print(b)
print(b[2, 1])
print(b[:, 1])       # 1열만 추출
print(np.shape(b))   # Array dimension as a tuple
print(np.size(b))    # Total number of elements
print(np.ndim(b))    # Number of dimensions
print(np.transpose(b))   # Comptutes matrix transpose

c = np.copy(b)      # Makes a deep copy. 메모리값도 새로운 것을 가진다.
print(id(c) == id(b)) 
print(c)
print(np.ravel(c))   # Makes the array one-dimensional

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
5
[1 3 5]
(3, 2)
6
2
[[0 2 4]
 [1 3 5]]
False
[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


### Mathematical Functions

In [10]:
import numpy as np

a = np.array([[1,2], [3,4]])
b = np.array([[11,12], [13,14]])

print(a + b)
print(a * b)
print(np.dot(a, b))   # matrix multiplication
print(np.inner(a,b))  # inner product of row vectors

[[12 14]
 [16 18]]
[[11 24]
 [39 56]]
[[37 40]
 [85 92]]
[[35 41]
 [81 95]]


In [15]:
import numpy as np 

a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
b = np.around(a)   # 반올림
c = np.floor(a)    # 0.5초과 제거
d = np.ceil(a)      # 0.5이상 반올림

print(b)
print(c)
print(d)

[-2.  2. -0.  1. 10.]
[-2.  1. -1.  0. 10.]
[-1.  2. -0.  1. 10.]


In [ ]:
import numpy as np

a = np.array([1.0, 5.55, 123, 0.567, 25.532])
b = np.around(a)
c = n