### Installation
- Use pip(Package Installer for Python)  
    - pip install numpy
    - pip install matplotlib
    ![use pip](https://user-images.githubusercontent.com/61931924/95999516-ebcae200-0e70-11eb-96f9-224cb48d2c5c.PNG)

### NumPy
- NumPy stands for 'Numerical Python'
    - A library consisting of multidimensional array objects and a collection of routines for processing of array
    
- Using NumPy, a developer can perform the follwing:
    - Mathematical and logical operations on arrays
    - Fourier transforms and routines for shape manipulation
    - Operations related to linear algebra
    - Random number generation

### Arrays
- The most important object defined in NumPy is the n-dimensional arrays type called __ndarray__
    - The elements of the array all have the same type
    - Items in the collections can be accessed using a zero-based index

In [8]:
import numpy as np

a = np.array([1,2,3])   # One-dimensional array
b = np.array([[1,2],
              [3,4]])   # Two dimensional array. 반드시 리스트 내에 포함해야 한다.
c = np.array([1,2,3,4,5], ndmin=2)   # To specify minimum number of dimensions
d = np.array([1,2,3], dtype=float)   # To specify desired data type for the array
print(a)
print(b)
print(c)
print(d)
a,b,c,d

[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1. 2. 3.]


(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]),
 array([[1, 2, 3, 4, 5]]),
 array([1., 2., 3.]))

여기서 말하는 dimension이란 차원의 수를 말하는데 2차원일 때는 행렬을 떠올리면 된다.

### Array Creation
- A new ndarray object can be constructed by any of the following array creation routines

In [9]:
import numpy as np

a = np.arange(5)        # Array of range(5)
b = np.arange(3,10,2)   # From 3 to 10 in increments of 2
c = np.zeros(5)   # Array of five zeros (default type is float)
d = np.ones(5)    # Array of five ones (default type is float)

print(a)
print(b)
print(c)
print(d)

a,b,c,d

[0 1 2 3 4]
[3 5 7 9]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


(array([0, 1, 2, 3, 4]),
 array([3, 5, 7, 9]),
 array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]))

np.arange , np.zeros , np.ones 세 가지를 제대로 알고 있자.

In [12]:
import numpy as np

a = np.eye(3)      # Produces square identity matrix
b = np.eye(3, 4)   # Identity matrix of size 3 × 4

# To produce an array of 5 elements equally spaced from 10 to 20
c = np.linspace(10, 20, 5)
d = np.linspace(10, 20, 3)

print(a)
print(b)
print(c)
print(d)
a,b,c,d


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[10.  12.5 15.  17.5 20. ]
[10. 15. 20.]


(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 array([10. , 12.5, 15. , 17.5, 20. ]),
 array([10., 15., 20.]))

### Getting Information and Changing Shapes
- We can get various information about an array and change its shape in a variety of ways

In [8]:
import numpy as np

a = np.arange(6)
print(a)

b = a.reshape(3,2)
print(b)
print(b[2, 1])
print(b[:, 1])       # 1열만 추출
print(np.shape(b))   # Array dimension as a tuple
print(np.size(b))    # Total number of elements
print(np.ndim(b))    # Number of dimensions
print(np.transpose(b))   # Comptutes matrix transpose

c = np.copy(b)      # Makes a deep copy. 메모리값도 새로운 것을 가진다.
print(id(c) == id(b)) 
print(c)
print(np.ravel(c))   # Makes the array one-dimensional

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
5
[1 3 5]
(3, 2)
6
2
[[0 2 4]
 [1 3 5]]
False
[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


### Mathematical Functions

In [10]:
import numpy as np

a = np.array([[1,2], [3,4]])
b = np.array([[11,12], [13,14]])

print(a + b)
print(a * b)
print(np.dot(a, b))   # matrix multiplication
print(np.inner(a,b))  # inner product of row vectors

[[12 14]
 [16 18]]
[[11 24]
 [39 56]]
[[37 40]
 [85 92]]
[[35 41]
 [81 95]]


In [15]:
import numpy as np 

a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
b = np.around(a)   # 반올림
c = np.floor(a)    # 0.5초과 제거
d = np.ceil(a)      # 0.5이상 반올림

print(b)
print(c)
print(d)

[-2.  2. -0.  1. 10.]
[-2.  1. -1.  0. 10.]
[-1.  2. -0.  1. 10.]


In [16]:
import numpy as np

a = np.array([1.0, 5.55, 123, 0.567, 25.532])
b = np.around(a)
c = np.around(a, decimals = 1)    # 소수점 첫째자리까지 반올림
d = np.around(a, decimals = -1)   # 둘째자리까지 반올림

### Statistical Functions

In [4]:
import numpy as np

a = np.array([[3,7,5], [8,4,3], [2,4,9]])
b = np.amin(a, 1)   # Minimum element along the rows (axis=1)
c = np.amin(a, 0)   # Minimum element along the cols (axis=0)
d = np.amin(a)      # Minimum element in the givenarray
e = np.amax(a, 1)
f = np.amax(a, 0)

print(b)
print(c)
print(d)
print(f)

[3 3 2]
[2 4 3]
2
[8 7 9]


In [7]:
a = np.array([1,2,3,4])
b = np.average(a)
c = np.std(a)
d = np.var(a)

print(b)
print(c)
print(d)

2.5
1.118033988749895
1.25


### Random Numbers

- rand는 표준정규분포를 따르는 표본을 행렬의 사이즈에 맞게 임의 추출.
- randint는 범위를 정해서 균등분포를 따르는 표본을 size 매개변수에 맞게 임의 추출

In [8]:
import numpy as np

b = np.random.rand(3,2)   # To produce a 3 × 2 matrix of random numbers uniformly distributed between 0 and 1
c = np.random.randint(3, 9, size=(2,4))   # To produce a 2 × 4 matrix of random integers uniformly distributed in range(3, 9)

print(b)
print(c)

[[0.82742405 0.76426634]
 [0.94335009 0.49223695]
 [0.08005107 0.10330784]]
[[7 8 7 8]
 [3 5 8 3]]


### linear Algebra

In [10]:
import numpy as np

a = np.array([[1,2], [3,4]])
b = np.array([[-4], [1]])
inv_a = np.linalg.solve(a, b)   # inverse of a
c = np.linalg.solve(a, b)       # compute x such that ax = b
d = np.linalg.det(a)            # determinant of a
e = np.linalg.eig(a)            # eigenvalues and eigenvectors of a

print(inv_a)
print(c)
print(d)
print(e)

[[ 9. ]
 [-6.5]]
[[ 9. ]
 [-6.5]]
-2.0000000000000004
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


![image](https://user-images.githubusercontent.com/61931924/96259217-42165d00-0ff8-11eb-99e6-460ceb1b0d05.png)

## Matplotlib
- Matplotlib is a plotting library for the Python programming language and its numerical mathematics extension NumPy
    - Provides an object-oriented API for embedding plots into applications using general-purpose GUI toolkits
    - Can handle line plot, images, histograms, bar/pie charts, tables, scatter plots, etc.

![matplotlib](https://user-images.githubusercontent.com/61931924/96259662-e39dae80-0ff8-11eb-8059-90fbd4dbca83.PNG)

### Pyplot Module

In [ ]:
from matplotlib import pyplot as plt

plt.plot([1,2,3], [1,4,9])   # Values for x and y axes
plt.plot([2,3,4], [5,6,7])   # Should be of the same lengths
plt.xlabel('Sequence')
plt.ylabel('Time')